---
title: "Análisis exploratorio"
author: "Antonio Álvarez Caballero"
date: "11 de mayo de 2016"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(plotly)
library(xgboost)
library(Matrix)
```

```{r aux, include = FALSE}
draw <- function(data, x, y1, y2, title) {
  ggplot(data_replay, aes_string(x) ) +
  geom_line(aes_string(y=y1, colour = shQuote('A')) ) +
  geom_line(aes_string(y=y2, colour = shQuote('B')) ) +
  ggtitle(title) +
  theme(legend.title=element_blank())
}
```



## Columnas

```{r readData}
data <- read.csv("../Datos/data.csv")
clean_data <- data[,!(colnames(data) %in% c("ReplayID","Duration"))]
data_replay <- data[data$ReplayID==114, ]
data_replay <- data_replay[, !(colnames(data_replay) %in% c("ReplayID","Duration"))]
print(colnames(data_replay))
```



## Minerales

```{r Minerales}
gg <- ggplot(data_replay, aes(Frame)) +
geom_point(aes(y=Minerals, colour = 'Ganador' )) +
geom_point(aes(y=EnemyMinerals, colour = 'Perdedor' )) +
ggtitle("Minerales") +
theme(legend.title=element_blank())

gg

ggplotly(gg)

```

## Minerales totales

```{r mineralesTotales}
gg <- ggplot(data_replay, aes(Frame)) +
geom_line(aes(y=TotalMinerals, colour = 'Ganador' )) +
geom_line(aes(y=EnemyTotalMinerals, colour = 'Perdedor' ))
gg

ggplotly(gg)
```

## Gas

```{r Gas}
gg <- ggplot(data_replay, aes(Frame)) +
geom_line(aes(y=Gas, colour = if(Winner=='A') as.factor('Ganador') else as.factor('Perdedor')  )) +
geom_line(aes(y=EnemyGas, colour = if(Winner=='B') as.factor('Ganador') else as.factor('Perdedor') )) +
ggtitle("Gas") +
theme(legend.title=element_blank())

gg
ggplotly(gg)
```

## Gas Total

```{r GasTotal}
gg <- ggplot(data_replay, aes(Frame)) +
geom_line(aes(y=TotalGas, colour = if(Winner=='A') as.factor('Ganador') else as.factor('Perdedor') )) +
geom_line(aes(y=EnemyTotalGas, colour = if(Winner=='B') as.factor('Ganador') else as.factor('Perdedor') )) +
ggtitle("Gas Total") +
theme(legend.title=element_blank())

gg
ggplotly(gg)
```

## Capacidad

```{r Supply}
gg <- ggplot(data_replay, aes(Frame)) +
geom_line(aes(y=Supply, colour = if(Winner=='A') as.factor('Ganador') else as.factor('Perdedor') )) +
geom_line(aes(y=EnemySupply, colour = if(Winner=='B') as.factor('Ganador') else as.factor('Perdedor') )) +
ggtitle("Supply") +
theme(legend.title=element_blank())

gg
ggplotly(gg)
```

## Capacidad Total

```{r SupplyTotal}
gg <- ggplot(data_replay, aes(Frame)) +
geom_line(aes(y=TotalSupply, colour = if(Winner=='A') as.factor('Ganador') else as.factor('Perdedor') )) +
geom_line(aes(y=EnemyTotalSupply, colour = if(Winner=='B') as.factor('Ganador') else as.factor('Perdedor') )) +
ggtitle("Supply Total") +
theme(legend.title=element_blank())

gg
ggplotly(gg)
```


## GroundUnit

```{r GroundUnitValue}
gg <- ggplot(data_replay, aes(Frame)) +
geom_line(aes(y=GroundUnitValue, colour = if(Winner=='A') as.factor('Ganador') else as.factor('Perdedor') )) +
geom_line(aes(y=EnemyGroundUnitValue, colour = if(Winner=='B') as.factor('Ganador') else as.factor('Perdedor') )) +
ggtitle("GroundUnitValue") +
theme(legend.title=element_blank())

gg
ggplotly(gg)
```

## GroundUnit observada

```{r observedGroundUnitValue}
gg <- ggplot(data_replay, aes(Frame)) +
geom_line(aes(y=AObservedEnemyGroundUnitValue, colour = if(Winner=='A') as.factor('Ganador') else as.factor('Perdedor') )) +
geom_line(aes(y=BObservedEnemyGroundUnitValue, colour = if(Winner=='B') as.factor('Ganador') else as.factor('Perdedor') )) +
ggtitle("Observed GroundUnitValue") +
theme(legend.title=element_blank())

gg
ggplotly(gg)
```


## Buildings

```{r buildingValue}

regressionA <- lm(BuildingValue ~ Frame, data=data_replay)
regressionB <- lm(EnemyBuildingValue ~ Frame, data=data_replay)

gg <- ggplot(data_replay, aes(Frame)) +
geom_line(aes(y=BuildingValue, colour = if(Winner=='A') as.factor('Ganador') else as.factor('Perdedor') )) +
geom_line(aes(y=EnemyBuildingValue, colour = if(Winner=='B') as.factor('Ganador') else as.factor('Perdedor') )) +
geom_abline(intercept=regressionA$coefficients[1], slope=regressionA$coefficients[2]) +
geom_abline(intercept=regressionB$coefficients[1], slope=regressionB$coefficients[2]) +
ggtitle("BuildingValue") +
theme(legend.title=element_blank())

gg
ggplotly(gg)

print(paste("Pendiente recta ganador:",regressionA$coefficients[2]))
print(paste("Pendiente recta perdedor:",regressionB$coefficients[2]))


```

## Buildings observadas

```{r observedBuildingValue}
gg <- ggplot(data_replay, aes(Frame)) +
geom_line(aes(y=AObservedEnemyBuildingValue, colour = if(Winner=='A') as.factor('Ganador') else as.factor('Perdedor') )) +
geom_line(aes(y=BObservedEnemyBuildingValue, colour = if(Winner=='B') as.factor('Ganador') else as.factor('Perdedor') )) +
ggtitle("Observed BuildingValue") +
theme(legend.title=element_blank())

gg
ggplotly(gg)
```

## AirUnits

```{r AirUnitValue}
gg <- ggplot(data_replay, aes(Frame)) +
geom_line(aes(y=AirUnitValue, colour = if(Winner=='A') as.factor('Ganador') else as.factor('Perdedor') )) +
geom_line(aes(y=EnemyAirUnitValue, colour = if(Winner=='B') as.factor('Ganador') else as.factor('Perdedor') )) +
ggtitle("AirUnitValue") +
theme(legend.title=element_blank())

gg

ggplotly(gg)
```

## AirUnits observadas

```{r observedAirUnitValue}
gg <- ggplot(data_replay, aes(Frame)) +
geom_line(aes(y=AObservedEnemyAirUnitValue, colour = if(Winner=='A') as.factor('Ganador') else as.factor('Perdedor') )) +
geom_line(aes(y=BObservedEnemyAirUnitValue, colour = if(Winner=='B') as.factor('Ganador') else as.factor('Perdedor') )) +
ggtitle("Observed AirUnitValue") +
theme(legend.title=element_blank())

gg
ggplotly(gg)
```

## ResourceValue

```{r ResourceValue}
gg <- ggplot(data_replay, aes(Frame)) +
geom_line(aes(y=AObservedResourceValue, colour = if(Winner=='A') as.factor('Ganador') else as.factor('Perdedor') )) +
geom_line(aes(y=BObservedResourceValue, colour = if(Winner=='B') as.factor('Ganador') else as.factor('Perdedor') )) +
ggtitle("ResourceValue") +
theme(legend.title=element_blank())

gg
ggplotly(gg)
```

## Selección de características (No terminado)

```{r featureSelection, eval = FALSE}
set.seed(7)
# load the library
library(mlbench)
library(caret)

# prepare training scheme
control <- trainControl(method="repeatedcv", number=10, repeats=3)
# train the model
model <- train(Winner~., data=data_replay, method="lvq", preProcess="scale", trControl=control)
# estimate variable importance
importance <- varImp(model, scale=FALSE)
# summarize importance
print(importance)
# plot importance
plot(importance)
```

```{r featureSelectionXGB, eval = FALSE}
sparse_matrix <- sparse.model.matrix(Winner ~ .-1, data = clean_data)
output_vector = data[,"Winner"] == "A"

bst <- xgboost(data = sparse_matrix, label = output_vector, max.depth = 48,
               eta = 0.1, nthread = 8, nround = 100,objective = "binary:logistic")

importance_matrix <- xgb.importance(colnames(clean_data), model = bst)
xgb.plot.importance(importance_matrix)
```


## Validación cruzada 5x2

```{r CV, eval = FALSE}
cv.res <- xgb.cv(data = sparse_matrix, label = output_vector, max.depth = 48,
               eta = 0.1, nthread = 8, nround = 100,objective = "binary:logistic", nfold = 5)
cv.res
```


